baseURL = 'https://fahoom.com/'
languageCode = 'en-gb'
title = "Fahim's Scrapbook"
theme = "typo"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "bookmarks"
url = "/bookmarks"

[params]
footerContent = " "


